### PR TITLE
Added the Initial Jamo and Medial Jamo fillers

### PR DESCRIPTION
**Pull request by ScraperMan2002**
So there are things called the Initial and Medial Jamo fillers that allow people to not actually put in an Initial Jamo and a Medial Jamo. It's actually REALLY important, as many Ancient Korean texts do not have an initial Jamo.
So please, actually accept this change.

### CODE REVIEW

**Comment by ScraperMan2002** [comment]
Hello?

**Comment by 5hwb** [comment]
Hi,

Do understand that I also have other priorities. Out of curiosity, are you studying at college/university? Do notice that if you're gonna speak like that to your employer, you'll greatly increase the chances of getting fired. Kindly moderate your tone next time.

**Comment by ScraperMan2002** [comment]
Really? I didn't know that this was some sort of offensive tone. I'm sorry. I just thought that, just like many notifications pile up on me, I miss a lot of very important stuff. And I thought you missed it as well, so that's why I tried to say something to reminded you.

**Comment by 5hwb** [comment]
Fair enough, although just saying 'Hello?' did come across as rude and demanding. I'll go write something like this instead: "Please review the PR whenever you can, thanks a lot!"

Please understand that I truly appreciate your contributions to this little project and that I'm not trying to criticise you, just trying to give some constructive feedback for next time.

**Review by 5hwb — APPROVED** [review]

**Pull request merged**
